import 'package:flutter/material.dart';
import '../../core/constants/app_colors.dart';
import '../../core/constants/app_dimensions.dart';

/// A centralized Scaffold wrapper that ensures consistent layout and styling across the app.
///
/// This widget wraps the standard [Scaffold] and provides common functionality such as:
/// - Consistent AppBar styling
/// - Automated SafeArea handling
/// - Standardized padding (optional)
/// - Unified background color handling
class AppScaffold extends StatelessWidget {
  /// The primary content of the screen.
  final Widget body;

  /// Optional title to simplify basic AppBars.
  /// If [title] is provided and [appBar] is null, a default AppBar is created.
  final String? title;

  /// Custom AppBar if more control is needed.
  /// Overrides the default AppBar generated by [title].
  final PreferredSizeWidget? appBar;

  /// Actions for the AppBar.
  /// Only used if [title] is provided and [appBar] is null.
  final List<Widget>? actions;

  /// Optional Floating Action Button.
  final Widget? floatingActionButton;

  /// Optional Bottom Navigation Bar.
  final Widget? bottomNavigationBar;

  /// Background color of the Scaffold.
  /// Defaults to [AppColors.scaffoldBackground] (or theme default) if null.
  final Color? backgroundColor;

  /// Whether to wrap the [body] in a [SafeArea].
  /// Defaults to true.
  final bool withSafeArea;

  /// Padding applied around the [body] content.
  /// Defaults to null. Use [AppDimensions.layoutPadding] or similar if standard padding is desired.
  final EdgeInsetsGeometry? padding;

  /// Whether to extend body behind the app bar.
  /// Defaults to false.
  final bool extendBodyBehindAppBar;

  const AppScaffold({
    super.key,
    required this.body,
    this.title,
    this.appBar,
    this.actions,
    this.floatingActionButton,
    this.bottomNavigationBar,
    this.backgroundColor,
    this.withSafeArea = true,
    this.padding,
    this.extendBodyBehindAppBar = false,
  });

  @override
  Widget build(BuildContext context) {
    // Construct the AppBar
    PreferredSizeWidget? effectiveAppBar = appBar;
    if (effectiveAppBar == null && title != null) {
      effectiveAppBar = AppBar(
        title: Text(title!),
        centerTitle: true,
        actions: actions,
        scrolledUnderElevation: 0,
        backgroundColor:
            backgroundColor ?? Theme.of(context).scaffoldBackgroundColor,
        elevation: 0,
      );
    }

    // Construct the Body
    Widget content = body;

    // Apply padding if provided
    if (padding != null) {
      content = Padding(padding: padding!, child: content);
    }

    // Apply SafeArea
    if (withSafeArea) {
      content = SafeArea(child: content);
    }

    return Scaffold(
      appBar: effectiveAppBar,
      body: content,
      floatingActionButton: floatingActionButton,
      bottomNavigationBar: bottomNavigationBar,
      backgroundColor: backgroundColor,
      extendBodyBehindAppBar: extendBodyBehindAppBar,
    );
  }
}
